// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4K2DAZgVim5NSqZyqK0G06-PZM_kSxs',
    appId: '1:569132470381:web:357403dc40c250081eef64',
    messagingSenderId: '569132470381',
    projectId: 'pomorush',
    authDomain: 'pomorush.firebaseapp.com',
    storageBucket: 'pomorush.appspot.com',
    measurementId: 'G-KKSCJMJ2ZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9P1RdCzZvg2LzpzERONtV1UrUoY_w438',
    appId: '1:569132470381:android:dd513fd3385a439e1eef64',
    messagingSenderId: '569132470381',
    projectId: 'pomorush',
    storageBucket: 'pomorush.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW_RnotE6Uc2lxNXu0lF4JszJpicwqdKc',
    appId: '1:569132470381:ios:1a0d98bee5e5c3281eef64',
    messagingSenderId: '569132470381',
    projectId: 'pomorush',
    storageBucket: 'pomorush.appspot.com',
    iosClientId: '569132470381-c5vcm1n4pr101v6d1ado7705qmlcefac.apps.googleusercontent.com',
    iosBundleId: 'com.pomo.rush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW_RnotE6Uc2lxNXu0lF4JszJpicwqdKc',
    appId: '1:569132470381:ios:2b3d42a0ac896beb1eef64',
    messagingSenderId: '569132470381',
    projectId: 'pomorush',
    storageBucket: 'pomorush.appspot.com',
    iosClientId: '569132470381-eem7nrdnd7fcqklgvivv0t1edgaks7if.apps.googleusercontent.com',
    iosBundleId: 'com.pomo.pomoRush.RunnerTests',
  );
}
